### ISSUE TITLE
Notworking. (still no audio)

### ISSUE THREAD

**Issue by DarrenOfficial** [Neko-Life/Discord-Screen-Share-Fix-Audio-on-Linux#1]
I use archlinux, with the kernel 5.16.4-arch1-1. and im using pulseaudio 15.0

**Comment by GlowingUmbreon** [comment]
It worked fine for me, did you read the instructions in the ReadMe?

**Comment by DarrenOfficial** [comment]
I don't know what I did wrong lastime, but I restarted my pc redo all the steps on the README and now it works
