### ISSUE TITLE
Every time I unplug my microphone, it stops recognizing it and I have to rerun the script

### ISSUE THREAD

**Issue by MrMcShroom** [Neko-Life/Discord-Screen-Share-Fix-Audio-on-Linux#7]
Running void linux. Works flawlessly until I reset or unplug my microphone, then it just doesn't work unless I run the script again. If I run the script again, it adds 2 new streams, and IDK how to remove the old ones.
Perhaps a secondary script to do that would be useful? Don't like having to rerun it each time I try to do it.

**Comment by Neko-Life** [comment]
you can run `pactl list | grep 'Module #\|=V1\|=V2'` and every module which has the Argument printed under it is the stream created by the script. Run `pactl unload-module <number>` for each module to remove the streams, there are usually 5 module.

Use pavucontrol to configure your input/output routing, it seems that you need to re-route your input every time the source changed.

PR is very welcome, maybe someone can write a sophisticated script to automate this?

**Comment by MrMcShroom** [comment]
Appreciate the feedback. I don't currently have any bash skills, but I'll keep it in mind if I ever get into it. Thanks.
