### ISSUE TITLE
Recording tab no longer switching to "app" or "mic+app"

### ISSUE THREAD

**Issue by JellyfishMunky** [Neko-Life/Discord-Screen-Share-Fix-Audio-on-Linux#9]
Program was working perfectly on PopOS! 22.04 without issue.

Something appears to now have changed (maybe something got updated) and whilst I can switch the playback option to 'app' and 'mic+app' the recording tab can display the option to select these but won't actually allow me to switch, either during playback or outside of it.

QjackCtl is showing everything looks routed just fine, but PulseAudio-qt just won't allow me to select what's clearly on display.

Again, not sure if this is an issue with the discord-scrshrwa.sh script or just a more general issue with PulseAudio itself now.

**Comment by Neko-Life** [comment]
what version of PulseAudio you have installed currently? what version did you use before the update? might be helpful https://support.system76.com/articles/audio/

**Comment by JellyfishMunky** [comment]
0.17.0 according to popOS!

**Comment by JellyfishMunky** [comment]
Issue was resolved by scrapping and reinstalling via apt-get instead of flatpak.

Version 5.0 now works just fine. :)
